package model

import "github.com/kvloginov/cup-of-team/backend/internal/domain"

// ErrorResponse for API errors
type ErrorResponse struct {
	Success bool   `json:"success"`
	Error   string `json:"error"`
}

// HealthResponse for health check
type HealthResponse struct {
	Status string `json:"status"`
}

// CreateTeamRequest
type CreateTeamRequest struct {
	// Team name, if already exists,
	Name string `json:"name"`
}

// CreateTeamResponse
type CreateTeamResponse struct {
	// Team ID - generated by the server.
	// Save it and share it only with your friends,
	// because at first it will be as a authorization method.
	ID string `json:"id"`
}

// AddToTeamRequest adds to the team a new user.
// If user already exists, overwrite the existing user.
type AddToTeamRequest struct {
	TeamID string      `json:"team_id"`
	User   domain.User `json:"user"`
}

type AddToTeamResponse struct {
	User domain.User `json:"user"`
}

type GetTeamRequest struct {
	TeamID string `json:"team_id"`
}

type GetTeamResponse struct {
	Team domain.Team `json:"team"`
}

type RemoveFromTeamRequest struct {
	TeamID string `json:"team_id"`
	UserID string `json:"user_id"`
}

type RemoveFromTeamResponse struct {
}
